% spotter2SWIFTcompliant.m - beta function to convert spotter to SWIFT-compliant structure
% J. Davis
% created on: 2021-10-18
% updates:
%          
% J. Davis, 2021-12-23, cleaned up and stored in Spotter utility folder in
%                       SWIFT-codes directory

function [spotterOut] = spotter2SWIFTcompliant(spotterIn)
SWIFTdateFormat = 'ddmmyyyy';

% NOTE: currently the creation of a new SWIFT-compliant structure drops data that Spotter provides but SWIFT may not
% TODO: update to include extra data. 
% https://www.mathworks.com/matlabcentral/answers/31273-how-to-update-struct-array-fields-with-mutiple-values
% see also: https://www.mathworks.com/matlabcentral/fileexchange/33866-disperse
%   https://www.mathworks.com/matlabcentral/answers/238820-assigning-an-array-to-structure-field
spotterOut = struct(...
    'ID', {spotterIn(:).ID}.',...
    'date',cellfun(@(x) datestr(x,SWIFTdateFormat),{spotterIn(:).datetime},'UniformOutput',false).',...
    'time',cellfun(@(x) datenum(x),{spotterIn(:).datetime},'UniformOutput',false).',...
    'lat',{spotterIn(:).latitude}.',...
    'lon',{spotterIn(:).longitude}.',...
    'peakwaveperiod',{spotterIn(:).peakPeriod}.',...
    'peakwavedirT',{spotterIn(:).peakDirection}.',...
    'sigwaveheight',{spotterIn(:).significantWaveHeight}.',...
    'wavespectra',cellfun(@(E,f,a1,b1,a2,b2) struct('energy',E,'freq',f,'a1',a1,'b1',b1,'a2',a2,'b2',b2),...
        {spotterIn(:).varianceDensity},...
        {spotterIn(:).frequency},...
        {spotterIn(:).a1},...
        {spotterIn(:).b1},...
        {spotterIn(:).a2},...
        {spotterIn(:).b2},...
        'UniformOutput',false).');
    
spotterOut = transpose(spotterOut); % transpose to match SWIFT dimensions
end 